# File generated by Flopy version 3.3.4 on 09/12/2021 at 15:44:52.
BEGIN attributes
  NAMES  well1  well2
  METHODS  stepwise  stepwise
END attributes

BEGIN timeseries
       1.00000000    -100.00000000      -5.00000000
     183.50000000     -50.00000000      -2.50000000
     366.00000000     -50.00000000      -2.50000000
END timeseries

